In [1]:
import numpy as np

In [2]:
minha_lista = [1,2,3]

Transformando uma lista em um array bympy

In [3]:
np.array(minha_lista)

array([1, 2, 3])

In [4]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

O método arange cria uma sequencia de numeros.


In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(3)

array([0., 0., 0.])

criando uma matriz zerada.
np.zeros((numeroDeLinhas,numeroDeColunas))

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.linspace(0,10,2)

array([ 0., 10.])

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.random.rand(5)

array([0.10013874, 0.47382886, 0.81069261, 0.06926233, 0.50267441])

In [14]:
np.random.rand(5, 4, 3)

array([[[0.28090888, 0.44206981, 0.8619674 ],
        [0.41732139, 0.5563464 , 0.1784348 ],
        [0.99289405, 0.46923966, 0.95935121],
        [0.75660044, 0.99007972, 0.71384549]],

       [[0.83485897, 0.22276977, 0.41370337],
        [0.89926713, 0.36398516, 0.63453514],
        [0.58749717, 0.61025875, 0.67603731],
        [0.82892701, 0.41876532, 0.02275049]],

       [[0.3877727 , 0.90138547, 0.88190199],
        [0.67068871, 0.79666077, 0.1087694 ],
        [0.20925356, 0.37379272, 0.72676202],
        [0.91641865, 0.01411847, 0.08806557]],

       [[0.78989089, 0.66423482, 0.31507854],
        [0.80463187, 0.96090711, 0.04886286],
        [0.6487603 , 0.63238369, 0.77037584],
        [0.10015453, 0.00890288, 0.97987707]],

       [[0.30583836, 0.98860129, 0.75991007],
        [0.86446508, 0.51220348, 0.25870403],
        [0.80499144, 0.53656289, 0.87982525],
        [0.72024862, 0.58160483, 0.62249975]]])

In [15]:
np.random.randn(4)

array([-0.63556386, -0.1660404 ,  0.36420696,  1.34282103])

In [16]:
np.random.randint(0,100,10)

array([85, 36, 21,  5, 37, 89,  2, 23,  8, 88])

In [20]:
arr = np.random.rand(25)

In [21]:
arr

array([0.56990569, 0.15851889, 0.01482162, 0.42778885, 0.73600268,
       0.20847789, 0.03832634, 0.89253165, 0.44079815, 0.59793339,
       0.79399319, 0.78673801, 0.7034637 , 0.2193362 , 0.01249598,
       0.38739557, 0.86211112, 0.69961104, 0.15345515, 0.77873527,
       0.06283848, 0.10101186, 0.76768336, 0.55894225, 0.05830925])

In [22]:
arr.reshape((5,5))

array([[0.56990569, 0.15851889, 0.01482162, 0.42778885, 0.73600268],
       [0.20847789, 0.03832634, 0.89253165, 0.44079815, 0.59793339],
       [0.79399319, 0.78673801, 0.7034637 , 0.2193362 , 0.01249598],
       [0.38739557, 0.86211112, 0.69961104, 0.15345515, 0.77873527],
       [0.06283848, 0.10101186, 0.76768336, 0.55894225, 0.05830925]])

In [24]:
arr.shape

(25,)

In [25]:
arr.max()


0.8925316548310075

In [26]:
arr.min()

0.01249598235191196

In [28]:
arr.argmax()

7

In [29]:
arr.argmin()

14